import { StyleSheet } from "@react-pdf/renderer";

export const quotationPdfStyles = StyleSheet.create({
  page: {
    paddingTop: 34,
    paddingBottom: 34,
    paddingHorizontal: 30,
    fontSize: 10,
    fontFamily: "Helvetica",
    color: "#111111",
    lineHeight: 1.45,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 18,
  },
  logo: { width: 86 },
  companyInfo: { textAlign: "right", fontSize: 9, width: "66%" },
  companyName: {
    fontFamily: "Helvetica-Bold",
    fontSize: 10,
    textTransform: "uppercase",
  },
  divider: { borderBottom: "0.5pt solid #cccccc", marginVertical: 8 },
  label: { color: "#555555" },
  bold: { fontFamily: "Helvetica-Bold" },
  sectionTitle: {
    fontFamily: "Helvetica-Bold",
    fontSize: 10,
    textTransform: "uppercase",
    marginBottom: 4,
    marginTop: 10,
  },
  table: { border: "0.5pt solid #b9b9b9" },
  tableHeader: { flexDirection: "row", backgroundColor: "#f0f0f0" },
  tableRow: { flexDirection: "row", borderTop: "0.5pt solid #b9b9b9" },
  tableCellBase: {
    padding: "4pt 6pt",
    borderRight: "0.5pt solid #b9b9b9",
    fontSize: 9,
  },
  colDescription: { flex: 2.4 },
  colCurrency: { flex: 0.9 },
  colUom: { flex: 1 },
  colAmount: { flex: 1 },
  colTotal: { flex: 1.2 },
  tableCellLast: { padding: "4pt 6pt", fontSize: 9 },
  tableCellRight: { textAlign: "right" },
  totalRow: {
    flexDirection: "row",
    borderTop: "0.5pt solid #b9b9b9",
    backgroundColor: "#f0f0f0",
  },
  signatoryBlock: { flexDirection: "row", marginTop: 18 },
  signatoryCol: { flex: 1 },
  signature: { width: 80, height: 30, objectFit: "contain", marginVertical: 4 },
  footer: { textAlign: "center", color: "#888888", fontSize: 9, marginTop: 16 },
});
